services:
  postgres:
    image: 'postgres:16'
    container_name: lykos_postgres
    environment:
      POSTGRES_DB: lykos_db
      POSTGRES_USER: lykos
      POSTGRES_PASSWORD: lykos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: lykos_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - ./scripts:/var/lib/pgadmin/scripts   # <- monta sua pasta local "scripts" no pgAdmin

volumes:
  postgres_data:
